- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable
      vars:
        URL: task.google.com
      ansible.builtin.debug:
          msg: Var URL - {{ URL }}

    - name: Print a variable
      ansible.builtin.debug:
        msg: Var URL - {{ URL }}

  ## KEY: val
  ## KEY: {{ var }}, then ansible expects it to be in double quotes
  #syntax: KEY: "{{ var }}"