- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  vars_files:
    - just-vars.yaml
  tasks:
    - name: Print a variable
      vars:
        URL: task.google.com
      ansible.builtin.debug:
          msg: Var URL - {{ URL }}

    - name: Print a variable
      ansible.builtin.debug:
        msg: Var URL - {{ URL }}

  ## KEY: val
  ## KEY: {{ var }}, then ansible expects it to be in double quotes
  #syntax: KEY: "{{ var }}"

  # Variable precedense - If same variable is declared in multiple, which will be picked by Ansible
  # Task Variable
  # Play Variable
