- name: Hashicorp Vault connect
  hosts: local
  connection: local
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Password - {{ lookup('community.hashi_vault.hashi_vault', 'secret=test/demo-ssh:password', token=vault_token, url='http://vault-azdevops.online:8200') }}"